# agents/documentation_agent.py
# Documentation Agent — genera y mantiene documentación técnica automáticamente.
# v2.0 Task-centric: ejecuta Tasks individuales asignadas por WorkflowEngine.

from core.interfaces.agent import Agent
from core.interfaces.task import Task


class DocumentationAgent(Agent):

    _TASK_HANDLERS = [
        "generate_readme",
        "generate_architecture",
        "generate_roadmap",
        "generate_runbook",
        "generate_adr",
        "generate_changelog",
        "analyze_repository",
        "update_readme",
        "generate_contributing",
        "analyze_local_project",
    ]

    def execute_task(self, task: Task) -> dict:
        handlers = {
            "generate_readme":       self._generate_readme,
            "generate_architecture": self._generate_architecture,
            "generate_roadmap":      self._generate_roadmap,
            "generate_runbook":      self._generate_runbook,
            "generate_adr":          self._generate_adr,
            "generate_changelog":    self._generate_changelog,
            "analyze_repository":    self._analyze_repository,
            "update_readme":         self._update_readme,
            "generate_contributing": self._generate_contributing,
            "analyze_local_project": self._analyze_local_project,
        }
        handler = handlers.get(task.type)
        if handler is None:
            raise ValueError(
                f"DocumentationAgent does not handle task type '{task.type}'. "
                f"Supported: {list(handlers.keys())}"
            )
        return handler(task.params)

    def run(self, task: str, context: dict = {}) -> dict:
        t = Task(type=task.replace(" ", "_"), params=context, assigned_to="documentation")
        return self.execute_task(t)

    def get_status(self) -> dict:
        return {
            "name": self.name,
            "role": self.role,
            "active": self.active,
            "tools": list(self.tools.keys()),
            "supported_tasks": self._TASK_HANDLERS,
        }

    def _generate_readme(self, params: dict) -> dict:
        github = self.get_tool("github")
        name        = params.get("name", "project")
        description = params.get("description", "")
        stack       = params.get("stack", [])
        org         = params.get("org", "lra-cloud-ops")
        repo        = params.get("repo", name)
        save        = params.get("save", False)
        stack_section = "\n".join(f"- {s}" for s in stack) if stack else "- TBD"
        content = f"""# {name}

{description}

## Overview

This project is part of **[LRA CloudOps](https://github.com/lra-cloud-ops)** and is
managed by **LRA AI Platform**.

## Tech Stack

{stack_section}

## Getting Started

```bash
git clone https://github.com/{org}/{name}.git
cd {name}
pip install -r requirements.txt
```

## Architecture

See [ARCHITECTURE.md](ARCHITECTURE.md) for the full architecture documentation.

## Roadmap

See [ROADMAP.md](ROADMAP.md) for the project roadmap.

## Contributing

See [CONTRIBUTING.md](CONTRIBUTING.md) for contribution guidelines.

---
*Generated by LRA AI Platform — Documentation Agent*
"""
        result = {"content": content, "file": "README.md"}
        if save and repo:
            try:
                github.execute("create_file", {
                    "repo": repo, "org": org, "path": "README.md",
                    "content": content,
                    "message": "docs: generate README.md (Documentation Agent)",
                })
                result["saved"] = True
                print(f"[DocumentationAgent] README.md saved to {org}/{repo}")
            except Exception as e:
                result["error"] = str(e)
        return result

    def _generate_architecture(self, params: dict) -> dict:
        github = self.get_tool("github")
        name        = params.get("name", "project")
        description = params.get("description", "")
        stack       = params.get("stack", [])
        components  = params.get("components", [])
        org         = params.get("org", "lra-cloud-ops")
        repo        = params.get("repo", name)
        save        = params.get("save", False)
        stack_section = "\n".join(f"- {s}" for s in stack) if stack else "- TBD"
        components_section = "\n".join(
            f"### {c['name']}\n{c.get('description', '')}\n" for c in components
        ) if components else "### Components\n\nTBD\n"
        content = f"""# Architecture — {name}

## Overview

{description}

## Tech Stack

{stack_section}

## Components

{components_section}

## Security Considerations

- Authentication and authorization
- Data encryption at rest and in transit
- Network security policies

---
*Generated by LRA AI Platform — Documentation Agent*
"""
        result = {"content": content, "file": "ARCHITECTURE.md"}
        if save and repo:
            try:
                github.execute("create_file", {
                    "repo": repo, "org": org, "path": "ARCHITECTURE.md",
                    "content": content,
                    "message": "docs: generate ARCHITECTURE.md (Documentation Agent)",
                })
                result["saved"] = True
                print(f"[DocumentationAgent] ARCHITECTURE.md saved to {org}/{repo}")
            except Exception as e:
                result["error"] = str(e)
        return result

    def _generate_roadmap(self, params: dict) -> dict:
        github = self.get_tool("github")
        name   = params.get("name", "project")
        phases = params.get("phases", [])
        org    = params.get("org", "lra-cloud-ops")
        repo   = params.get("repo", name)
        save   = params.get("save", False)
        if not phases:
            phases = [
                {"name": "Phase 1 — Foundation", "items": ["Initial setup", "Core infrastructure", "Basic documentation"]},
                {"name": "Phase 2 — Development", "items": ["Core features", "Testing", "CI/CD pipeline"]},
                {"name": "Phase 3 — Production", "items": ["Security hardening", "Monitoring", "Production deployment"]},
            ]
        phases_content = ""
        for phase in phases:
            items = "\n".join(f"- [ ] {item}" for item in phase.get("items", []))
            phases_content += f"\n## {phase['name']}\n\n{items}\n"
        content = f"# Roadmap — {name}\n{phases_content}\n---\n*Generated by LRA AI Platform — Documentation Agent*\n"
        result = {"content": content, "file": "ROADMAP.md"}
        if save and repo:
            try:
                github.execute("create_file", {
                    "repo": repo, "org": org, "path": "ROADMAP.md",
                    "content": content, "message": "docs: generate ROADMAP.md",
                })
                result["saved"] = True
            except Exception as e:
                result["error"] = str(e)
        return result

    def _generate_runbook(self, params: dict) -> dict:
        github  = self.get_tool("github")
        service = params.get("service", "service")
        org     = params.get("org", "lra-cloud-ops")
        repo    = params.get("repo")
        save    = params.get("save", False)
        steps   = params.get("steps", [])
        steps_content = "\n".join(
            f"### Step {i+1}: {s['name']}\n\n{s.get('description','')}\n\n```bash\n{s.get('command','# command here')}\n```\n"
            for i, s in enumerate(steps)
        ) if steps else "### Steps\n\nTBD\n"
        content = f"""# Runbook — {service}

## Overview

Operational runbook for **{service}**.

## Procedure

{steps_content}

## Rollback

```bash
# Rollback procedure here
```

---
*Generated by LRA AI Platform — Documentation Agent*
"""
        result = {"content": content, "file": f"docs/runbooks/{service}-runbook.md"}
        if save and repo:
            try:
                github.execute("create_file", {
                    "repo": repo, "org": org,
                    "path": f"docs/runbooks/{service}-runbook.md",
                    "content": content, "message": f"docs: add runbook for {service}",
                })
                result["saved"] = True
            except Exception as e:
                result["error"] = str(e)
        return result

    def _generate_adr(self, params: dict) -> dict:
        github       = self.get_tool("github")
        number       = params.get("number", "001")
        title        = params.get("title", "Decision Title")
        context      = params.get("context", "")
        decision     = params.get("decision", "")
        consequences = params.get("consequences", "")
        org          = params.get("org", "lra-cloud-ops")
        repo         = params.get("repo")
        save         = params.get("save", False)
        from datetime import date
        content = f"""# ADR-{number}: {title}

**Status:** Accepted
**Date:** {date.today().isoformat()}

## Context

{context or "Describe the context and problem statement here."}

## Decision

{decision or "Describe the decision that was made."}

## Consequences

{consequences or "Describe the resulting context after applying the decision."}

---
*Generated by LRA AI Platform — Documentation Agent*
"""
        path_file = f"docs/adr/ADR-{number}-{title.lower().replace(' ', '-')}.md"
        result = {"content": content, "file": path_file}
        if save and repo:
            try:
                github.execute("create_file", {
                    "repo": repo, "org": org, "path": path_file,
                    "content": content, "message": f"docs: add ADR-{number}: {title}",
                })
                result["saved"] = True
            except Exception as e:
                result["error"] = str(e)
        return result

    def _generate_changelog(self, params: dict) -> dict:
        github  = self.get_tool("github")
        name    = params.get("name", "project")
        org     = params.get("org", "lra-cloud-ops")
        repo    = params.get("repo", name)
        save    = params.get("save", False)
        entries = params.get("entries", [])
        from datetime import date
        entries_content = ""
        if entries:
            for entry in entries:
                version  = entry.get("version", "0.1.0")
                date_str = entry.get("date", str(date.today()))
                changes  = "\n".join(f"- {c}" for c in entry.get("changes", []))
                entries_content += f"\n## [{version}] - {date_str}\n\n{changes}\n"
        else:
            entries_content = f"\n## [0.1.0] - {date.today()}\n\n- Initial release\n"
        content = f"# Changelog — {name}\n\nAll notable changes to this project will be documented in this file.\n{entries_content}\n---\n*Generated by LRA AI Platform — Documentation Agent*\n"
        result = {"content": content, "file": "CHANGELOG.md"}
        if save and repo:
            try:
                github.execute("create_file", {
                    "repo": repo, "org": org, "path": "CHANGELOG.md",
                    "content": content, "message": "docs: generate CHANGELOG.md",
                })
                result["saved"] = True
            except Exception as e:
                result["error"] = str(e)
        return result

    def _analyze_repository(self, params: dict) -> dict:
        github = self.get_tool("github")
        repo   = params.get("repo")
        org    = params.get("org", "lra-cloud-ops")
        save   = params.get("save", False)
        print(f"[DocumentationAgent] Analyzing repository {org}/{repo}...")
        repo_info   = github.execute("get_repo", {"repo": repo, "org": org})
        description = repo_info.get("description", "")
        docs_generated = {}
        for task_type, gen_fn in [
            ("generate_readme",       self._generate_readme),
            ("generate_architecture", self._generate_architecture),
            ("generate_roadmap",      self._generate_roadmap),
            ("generate_contributing", self._generate_contributing),
        ]:
            result = gen_fn({"name": repo, "description": description, "org": org, "repo": repo, "save": save})
            key = {"generate_readme": "README.md", "generate_architecture": "ARCHITECTURE.md",
                   "generate_roadmap": "ROADMAP.md", "generate_contributing": "CONTRIBUTING.md"}[task_type]
            docs_generated[key] = result.get("saved", False)
        print(f"[DocumentationAgent] Analysis complete for {org}/{repo}")
        return {"repo": f"{org}/{repo}", "description": description, "docs_generated": docs_generated, "total_docs": len(docs_generated)}

    def _update_readme(self, params: dict) -> dict:
        github  = self.get_tool("github")
        repo    = params.get("repo")
        org     = params.get("org", "lra-cloud-ops")
        existing = github.execute("get_file", {"repo": repo, "org": org, "path": "README.md"})
        new_content = params.get("content", existing.get("content", ""))
        result = github.execute("update_file", {
            "repo": repo, "org": org, "path": "README.md",
            "content": new_content,
            "message": params.get("message", "docs: update README.md (Documentation Agent)"),
        })
        print(f"[DocumentationAgent] README.md updated in {org}/{repo}")
        return result

    def _generate_contributing(self, params: dict) -> dict:
        github = self.get_tool("github")
        name   = params.get("name", "project")
        org    = params.get("org", "lra-cloud-ops")
        repo   = params.get("repo", name)
        save   = params.get("save", False)
        content = f"""# Contributing to {name}

Thank you for your interest in contributing to **{name}**!

## Pull Requests

1. Fork the repository
2. Create a feature branch: `git checkout -b feature/my-feature`
3. Commit: `git commit -m "feat: add my feature"`
4. Push and open a Pull Request

## Commit Convention

- feat: new feature
- fix: bug fix
- docs: documentation
- chore: maintenance

## Development Setup

```bash
git clone https://github.com/{org}/{name}.git
cd {name}
pip install -r requirements.txt
```

---
*Generated by LRA AI Platform — Documentation Agent*
"""
        result = {"content": content, "file": "CONTRIBUTING.md"}
        if save and repo:
            try:
                github.execute("create_file", {
                    "repo": repo, "org": org, "path": "CONTRIBUTING.md",
                    "content": content, "message": "docs: generate CONTRIBUTING.md",
                })
                result["saved"] = True
            except Exception as e:
                result["error"] = str(e)
        return result

    def _analyze_local_project(self, params: dict) -> dict:
        local   = self.get_tool("local")
        path    = params.get("path", ".")
        save    = params.get("save", False)
        save_to = params.get("save_to", "local")
        org     = params.get("org", "lra-cloud-ops")
        repo    = params.get("repo")
        print(f"[DocumentationAgent] Analyzing local project: {path}")
        analysis = local.execute("analyze_project", {"path": path})
        if "error" in analysis:
            return analysis
        name        = analysis.get("name", "project")
        stack       = analysis.get("stack", {}).get("technologies", [])
        description = analysis.get("info", {}).get("description", "")
        print(f"[DocumentationAgent] Project: {name}")
        print(f"[DocumentationAgent] Stack: {', '.join(stack)}")
        docs = {
            "README.md":      self._generate_readme({"name": name, "description": description, "stack": stack, "org": org, "repo": repo or name, "save": False}).get("content", ""),
            "ARCHITECTURE.md": self._generate_architecture({"name": name, "description": description, "stack": stack, "org": org, "repo": repo or name, "save": False}).get("content", ""),
            "ROADMAP.md":     self._generate_roadmap({"name": name, "org": org, "repo": repo or name, "save": False}).get("content", ""),
            "CONTRIBUTING.md": self._generate_contributing({"name": name, "org": org, "repo": repo or name, "save": False}).get("content", ""),
        }
        docs_generated = {}
        if save:
            if save_to == "local":
                for filename, content in docs.items():
                    result = local.execute("save_file", {"path": f"{path}/{filename}", "content": content})
                    docs_generated[filename] = result.get("saved", False)
                    if result.get("saved"):
                        print(f"[DocumentationAgent] {filename} saved to {path}")
            elif save_to == "github" and repo:
                github = self.get_tool("github")
                for filename, content in docs.items():
                    try:
                        github.execute("create_file", {"repo": repo, "org": org, "path": filename, "content": content, "message": f"docs: generate {filename}"})
                        docs_generated[filename] = True
                        print(f"[DocumentationAgent] {filename} saved to {org}/{repo}")
                    except Exception:
                        docs_generated[filename] = False
        else:
            docs_generated = {k: False for k in docs.keys()}
        print(f"[DocumentationAgent] Local analysis complete for {path}")
        return {
            "path": path, "name": name, "stack": stack,
            "description": description, "docs_generated": docs_generated,
            "docs_content": docs,
            "total_files": analysis.get("info", {}).get("total_files", 0),
        }
