# agents/documentation_agent.py
# Documentation Agent — genera y mantiene documentación técnica automáticamente.
# v2.0 Task-centric: ejecuta Tasks individuales asignadas por WorkflowEngine.

from core.interfaces.agent import Agent
from core.interfaces.task import Task


class DocumentationAgent(Agent):
    """
    Documentation Agent de LRA AI Platform.

    Especialidad: generación y mantenimiento automático de documentación
    técnica para proyectos de DevOps y Platform Engineering.

    Tasks que sabe ejecutar:
        generate_readme          → genera README.md completo
        generate_architecture    → genera ARCHITECTURE.md
        generate_roadmap         → genera ROADMAP.md
        generate_runbook         → genera Runbook para un servicio
        generate_adr             → genera un Architecture Decision Record
        generate_changelog       → genera CHANGELOG.md
        analyze_repository       → analiza un repo y genera doc completa
        update_readme            → actualiza README existente
        generate_contributing    → genera CONTRIBUTING.md

    Tools que usa:
        - github → leer repos, crear y actualizar archivos
    """

    _TASK_HANDLERS = [
        "generate_readme",
        "generate_architecture",
        "generate_roadmap",
        "generate_runbook",
        "generate_adr",
        "generate_changelog",
        "analyze_repository",
        "update_readme",
        "generate_contributing",
    ]

    def execute_task(self, task: Task) -> dict:
        handlers = {
            "generate_readme":       self._generate_readme,
            "generate_architecture": self._generate_architecture,
            "generate_roadmap":      self._generate_roadmap,
            "generate_runbook":      self._generate_runbook,
            "generate_adr":          self._generate_adr,
            "generate_changelog":    self._generate_changelog,
            "analyze_repository":    self._analyze_repository,
            "update_readme":         self._update_readme,
            "generate_contributing": self._generate_contributing,
        }

        handler = handlers.get(task.type)
        if handler is None:
            raise ValueError(
                f"DocumentationAgent does not handle task type '{task.type}'. "
                f"Supported: {list(handlers.keys())}"
            )
        return handler(task.params)

    def run(self, task: str, context: dict = {}) -> dict:
        """Compatibilidad v1.0."""
        t = Task(type=task.replace(" ", "_"), params=context, assigned_to="documentation")
        return self.execute_task(t)

    def get_status(self) -> dict:
        return {
            "name": self.name,
            "role": self.role,
            "active": self.active,
            "tools": list(self.tools.keys()),
            "supported_tasks": self._TASK_HANDLERS,
        }

    # --- Implementaciones ---

    def _generate_readme(self, params: dict) -> dict:
        """Genera un README.md completo para un proyecto."""
        github = self.get_tool("github")
        name        = params.get("name", "project")
        description = params.get("description", "")
        stack       = params.get("stack", [])
        org         = params.get("org", "lra-cloud-ops")
        repo        = params.get("repo", name)
        save        = params.get("save", False)

        stack_section = "\n".join(f"- {s}" for s in stack) if stack else "- TBD"

        content = f"""# {name}

{description}

## Overview

This project is part of **[LRA CloudOps](https://github.com/lra-cloud-ops)** and is
managed by **LRA AI Platform**.

## Tech Stack

{stack_section}

## Getting Started

### Prerequisites

```bash
# Clone the repository
git clone https://github.com/{org}/{name}.git
cd {name}
```

### Installation

```bash
# Install dependencies
pip install -r requirements.txt  # Python
# or
npm install                       # Node.js
```

## Usage

```bash
# Add usage examples here
```

## Architecture

See [ARCHITECTURE.md](ARCHITECTURE.md) for the full architecture documentation.

## Roadmap

See [ROADMAP.md](ROADMAP.md) for the project roadmap.

## Contributing

See [CONTRIBUTING.md](CONTRIBUTING.md) for contribution guidelines.

## License

MIT License — see [LICENSE](LICENSE) for details.

---
*Generated by LRA AI Platform — Documentation Agent*
"""

        result = {"content": content, "file": "README.md"}
        if save and repo:
            try:
                github.execute("create_file", {
                    "repo": repo, "org": org,
                    "path": "README.md", "content": content,
                    "message": "docs: generate README.md (Documentation Agent)",
                })
                result["saved"] = True
                print(f"[DocumentationAgent] README.md saved to {org}/{repo}")
            except Exception as e:
                result["error"] = str(e)

        return result

    def _generate_architecture(self, params: dict) -> dict:
        """Genera un ARCHITECTURE.md detallado."""
        github = self.get_tool("github")
        name        = params.get("name", "project")
        description = params.get("description", "")
        stack       = params.get("stack", [])
        components  = params.get("components", [])
        org         = params.get("org", "lra-cloud-ops")
        repo        = params.get("repo", name)
        save        = params.get("save", False)

        stack_section = "\n".join(f"- {s}" for s in stack) if stack else "- TBD"
        components_section = "\n".join(
            f"### {c['name']}\n{c.get('description', '')}\n"
            for c in components
        ) if components else "### Components\n\nTBD\n"

        content = f"""# Architecture — {name}

## Overview

{description}

## Tech Stack

{stack_section}

## Architecture Diagram

{name}
│
├── Component A
├── Component B
└── Component C

## Components

{components_section}

## Data Flow

User → API → Service → Database

## Design Decisions

| Decision | Rationale | Date |
|---|---|---|
| TBD | TBD | TBD |

## ADR (Architecture Decision Records)

- [ADR-001](docs/adr/ADR-001.md): Initial architecture definition

## Security Considerations

- Authentication and authorization
- Data encryption at rest and in transit
- Network security policies

## Scalability

- Horizontal scaling strategy
- Caching strategy
- Load balancing

---
*Generated by LRA AI Platform — Documentation Agent*
"""

        result = {"content": content, "file": "ARCHITECTURE.md"}
        if save and repo:
            try:
                github.execute("create_file", {
                    "repo": repo, "org": org,
                    "path": "ARCHITECTURE.md", "content": content,
                    "message": "docs: generate ARCHITECTURE.md (Documentation Agent)",
                })
                result["saved"] = True
                print(f"[DocumentationAgent] ARCHITECTURE.md saved to {org}/{repo}")
            except Exception as e:
                result["error"] = str(e)

        return result

    def _generate_roadmap(self, params: dict) -> dict:
        """Genera un ROADMAP.md con fases de desarrollo."""
        github = self.get_tool("github")
        name   = params.get("name", "project")
        phases = params.get("phases", [])
        org    = params.get("org", "lra-cloud-ops")
        repo   = params.get("repo", name)
        save   = params.get("save", False)

        if not phases:
            phases = [
                {"name": "Phase 1 — Foundation", "items": ["Initial setup", "Core infrastructure", "Basic documentation"]},
                {"name": "Phase 2 — Development", "items": ["Core features", "Testing", "CI/CD pipeline"]},
                {"name": "Phase 3 — Production", "items": ["Security hardening", "Monitoring", "Production deployment"]},
            ]

        phases_content = ""
        for phase in phases:
            items = "\n".join(f"- [ ] {item}" for item in phase.get("items", []))
            phases_content += f"\n## {phase['name']}\n\n{items}\n"

        content = f"""# Roadmap — {name}
{phases_content}

---
*Generated by LRA AI Platform — Documentation Agent*
"""

        result = {"content": content, "file": "ROADMAP.md"}
        if save and repo:
            try:
                github.execute("create_file", {
                    "repo": repo, "org": org,
                    "path": "ROADMAP.md", "content": content,
                    "message": "docs: generate ROADMAP.md (Documentation Agent)",
                })
                result["saved"] = True
            except Exception as e:
                result["error"] = str(e)

        return result

    def _generate_runbook(self, params: dict) -> dict:
        """Genera un Runbook para un servicio o procedimiento."""
        github   = self.get_tool("github")
        service  = params.get("service", "service")
        org      = params.get("org", "lra-cloud-ops")
        repo     = params.get("repo")
        save     = params.get("save", False)
        steps    = params.get("steps", [])

        steps_content = "\n".join(
            f"### Step {i+1}: {s['name']}\n\n{s.get('description', '')}\n\n```bash\n{s.get('command', '# command here')}\n```\n"
            for i, s in enumerate(steps)
        ) if steps else "### Steps\n\nTBD\n"

        content = f"""# Runbook — {service}

## Overview

Operational runbook for **{service}**.

## Prerequisites

- Access to the relevant systems
- Required permissions
- Tools installed

## Procedure

{steps_content}

## Rollback

If something goes wrong:

```bash
# Rollback procedure here
```

## Contacts

| Role | Contact |
|---|---|
| On-call | TBD |
| Team lead | TBD |

## Related Documents

- [ARCHITECTURE.md](../ARCHITECTURE.md)
- [CONTRIBUTING.md](../CONTRIBUTING.md)

---
*Generated by LRA AI Platform — Documentation Agent*
"""

        result = {"content": content, "file": f"docs/runbooks/{service}-runbook.md"}
        if save and repo:
            try:
                github.execute("create_file", {
                    "repo": repo, "org": org,
                    "path": f"docs/runbooks/{service}-runbook.md",
                    "content": content,
                    "message": f"docs: add runbook for {service}",
                })
                result["saved"] = True
                print(f"[DocumentationAgent] Runbook saved for {service}")
            except Exception as e:
                result["error"] = str(e)

        return result

    def _generate_adr(self, params: dict) -> dict:
        """Genera un Architecture Decision Record."""
        github  = self.get_tool("github")
        number  = params.get("number", "001")
        title   = params.get("title", "Decision Title")
        context = params.get("context", "")
        decision = params.get("decision", "")
        consequences = params.get("consequences", "")
        org     = params.get("org", "lra-cloud-ops")
        repo    = params.get("repo")
        save    = params.get("save", False)
        from datetime import date

        content = f"""# ADR-{number}: {title}

**Status:** Accepted
**Date:** {date.today().isoformat()}

## Context

{context or "Describe the context and problem statement here."}

## Decision

{decision or "Describe the decision that was made."}

## Consequences

{consequences or "Describe the resulting context after applying the decision."}

## Alternatives Considered

- Alternative A: ...
- Alternative B: ...

---
*Generated by LRA AI Platform — Documentation Agent*
"""

        result = {"content": content, "file": f"docs/adr/ADR-{number}-{title.lower().replace(' ', '-')}.md"}
        if save and repo:
            try:
                path = f"docs/adr/ADR-{number}-{title.lower().replace(' ', '-')}.md"
                github.execute("create_file", {
                    "repo": repo, "org": org,
                    "path": path, "content": content,
                    "message": f"docs: add ADR-{number}: {title}",
                })
                result["saved"] = True
                print(f"[DocumentationAgent] ADR-{number} saved")
            except Exception as e:
                result["error"] = str(e)

        return result

    def _generate_changelog(self, params: dict) -> dict:
        """Genera un CHANGELOG.md."""
        github  = self.get_tool("github")
        name    = params.get("name", "project")
        org     = params.get("org", "lra-cloud-ops")
        repo    = params.get("repo", name)
        save    = params.get("save", False)
        entries = params.get("entries", [])

        from datetime import date
        entries_content = ""
        if entries:
            for entry in entries:
                version = entry.get("version", "0.1.0")
                date_str = entry.get("date", str(date.today()))
                changes = "\n".join(f"- {c}" for c in entry.get("changes", []))
                entries_content += f"\n## [{version}] - {date_str}\n\n{changes}\n"
        else:
            entries_content = f"\n## [0.1.0] - {date.today()}\n\n- Initial release\n"

        content = f"""# Changelog — {name}

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

{entries_content}

---
*Generated by LRA AI Platform — Documentation Agent*
"""

        result = {"content": content, "file": "CHANGELOG.md"}
        if save and repo:
            try:
                github.execute("create_file", {
                    "repo": repo, "org": org,
                    "path": "CHANGELOG.md", "content": content,
                    "message": "docs: generate CHANGELOG.md",
                })
                result["saved"] = True
            except Exception as e:
                result["error"] = str(e)

        return result

    def _analyze_repository(self, params: dict) -> dict:
        """
        Analiza un repositorio existente en GitHub y genera
        documentación completa basada en su contenido.
        """
        github = self.get_tool("github")
        repo   = params.get("repo")
        org    = params.get("org", "lra-cloud-ops")
        save   = params.get("save", False)

        print(f"[DocumentationAgent] Analyzing repository {org}/{repo}...")

        repo_info = github.execute("get_repo", {"repo": repo, "org": org})
        description = repo_info.get("description", "")
        default_branch = repo_info.get("default_branch", "main")

        docs_generated = {}

        readme = self._generate_readme({
            "name": repo,
            "description": description,
            "org": org,
            "repo": repo,
            "save": save,
        })
        docs_generated["README.md"] = readme.get("saved", False)

        architecture = self._generate_architecture({
            "name": repo,
            "description": description,
            "org": org,
            "repo": repo,
            "save": save,
        })
        docs_generated["ARCHITECTURE.md"] = architecture.get("saved", False)

        roadmap = self._generate_roadmap({
            "name": repo,
            "org": org,
            "repo": repo,
            "save": save,
        })
        docs_generated["ROADMAP.md"] = roadmap.get("saved", False)

        contributing = self._generate_contributing({
            "name": repo,
            "org": org,
            "repo": repo,
            "save": save,
        })
        docs_generated["CONTRIBUTING.md"] = contributing.get("saved", False)

        print(f"[DocumentationAgent] Analysis complete for {org}/{repo}")
        return {
            "repo": f"{org}/{repo}",
            "description": description,
            "docs_generated": docs_generated,
            "total_docs": len(docs_generated),
        }

    def _update_readme(self, params: dict) -> dict:
        """Actualiza un README existente en GitHub."""
        github = self.get_tool("github")
        repo   = params.get("repo")
        org    = params.get("org", "lra-cloud-ops")

        existing = github.execute("get_file", {
            "repo": repo, "org": org, "path": "README.md"
        })

        new_content = params.get("content", existing.get("content", ""))
        message     = params.get("message", "docs: update README.md (Documentation Agent)")

        result = github.execute("update_file", {
            "repo": repo, "org": org,
            "path": "README.md",
            "content": new_content,
            "message": message,
        })
        print(f"[DocumentationAgent] README.md updated in {org}/{repo}")
        return result

    def _generate_contributing(self, params: dict) -> dict:
        """Genera un CONTRIBUTING.md."""
        github = self.get_tool("github")
        name   = params.get("name", "project")
        org    = params.get("org", "lra-cloud-ops")
        repo   = params.get("repo", name)
        save   = params.get("save", False)

        content = f"""# Contributing to {name}

Thank you for your interest in contributing to **{name}**!

## How to Contribute

### Reporting Issues

- Use the [GitHub Issues](https://github.com/{org}/{name}/issues) page
- Include a clear description of the problem
- Add steps to reproduce the issue
- Include relevant logs or screenshots

### Pull Requests

1. Fork the repository
2. Create a feature branch: `git checkout -b feature/my-feature`
3. Make your changes
4. Run tests: `make test`
5. Commit: `git commit -m "feat: add my feature"`
6. Push: `git push origin feature/my-feature`
7. Open a Pull Request

### Commit Convention

We follow [Conventional Commits](https://www.conventionalcommits.org/):

feat: add new feature
fix: fix a bug
docs: update documentation
chore: maintenance tasks
refactor: code refactoring
test: add or update tests

### Code Style

- Python: PEP 8
- Use meaningful variable and function names
- Add docstrings to all functions
- Write tests for new features

## Development Setup

```bash
git clone https://github.com/{org}/{name}.git
cd {name}
pip install -r requirements.txt
```

## Questions?

Open an issue or reach out to the maintainers.

---
*Generated by LRA AI Platform — Documentation Agent*
"""

        result = {"content": content, "file": "CONTRIBUTING.md"}
        if save and repo:
            try:
                github.execute("create_file", {
                    "repo": repo, "org": org,
                    "path": "CONTRIBUTING.md", "content": content,
                    "message": "docs: generate CONTRIBUTING.md",
                })
                result["saved"] = True
                print(f"[DocumentationAgent] CONTRIBUTING.md saved")
            except Exception as e:
                result["error"] = str(e)

        return result
    
    